import { parseCurrentWeatherData, parseForecastWeatherData } from './parseApiResponse';

const resetError = () => {
  const output = document.getElementById('output');
  output.textContent = '';
};

const emptyContainer = () => {
  const container = document.getElementById('content');
  const containerDivs = container.getElementsByTagName('div');
  while (containerDivs[0]) {
    containerDivs[0].parentNode.removeChild(containerDivs[0]);
  }
};

const displayForecastDataImperial = () => {
  const contentDiv = document.getElementById('content');
  const forecastDataDiv = document.createElement('div');
  forecastDataDiv.id = 'forecast';
  parseForecastWeatherData().then((data) => {
    console.log(data);
    const dayZeroDiv = document.createElement('div');
    const dayZeroHeader = document.createElement('h4');
    dayZeroHeader.textContent = `Forecast data for today: ${data[0].date} `;
    dayZeroDiv.appendChild(dayZeroHeader);
    const dayZeroImg = document.createElement('img');
    dayZeroImg.src = `http:${data[0].icon}`;
    dayZeroDiv.appendChild(dayZeroImg);
    const dayZeroDesc = document.createElement('p');
    dayZeroDesc.textContent = `Forecast: ${data[0].text}`;
    dayZeroDiv.appendChild(dayZeroDesc);
    const dayZeroList = document.createElement('ul');
    const avgHumidity0 = document.createElement('li');
    avgHumidity0.textContent = `Humidity: ${data[0].avghumidity}%`;
    const avgTemp0 = document.createElement('li');
    avgTemp0.textContent = `Average Temp: ${data[0].avgtemp_f}°F`;
    const avgvis0 = document.createElement('li');
    avgvis0.textContent = `Average Visibility: ${data[0].avgvis_miles} miles`;
    const rainChance0 = document.createElement('li');
    rainChance0.textContent = `Chance of Rain: ${data[0].daily_chance_of_rain}%`;
    const snowChance0 = document.createElement('li');
    snowChance0.textContent = `Chance of Snow: ${data[0].daily_chance_of_snow}%`;
    const maxTemp0 = document.createElement('li');
    maxTemp0.textContent = `Max Temp: ${data[0].maxtemp_f}°F`;
    const maxWind0 = document.createElement('li');
    maxWind0.textContent = `Max Wind Speed: ${data[0].maxwind_mph}`;
    const mintemp0 = document.createElement('li');
    mintemp0.textContent = `Min Temp: ${data[0].mintemp_f}°F`;
    const moonPhase0 = document.createElement('li');
    moonPhase0.textContent = `Moon Phase: ${data[0].moon_phase}`;
    const moonRise0 = document.createElement('li');
    moonRise0.textContent = `Moonrise: ${data[0].moonrise}`;
    const moonSet0 = document.createElement('li');
    moonSet0.textContent = `Moonset: ${data[0].moonset}`;
    const sunRise0 = document.createElement('li');
    sunRise0.textContent = `Sunrise: ${data[0].sunrise}`;
    const sunSet0 = document.createElement('li');
    sunSet0.textContent = `Sunset: ${data[0].sunset}`;
    const precip0 = document.createElement('li');
    precip0.textContent = `Total Precipitation: ${data[0].totalprecip_in} inches`;
    const totalSnow0 = document.createElement('li');
    totalSnow0.textContent = `Total Snow: ${data[0].totalsnow_cm} cm`;
    const uv0 = document.createElement('li');
    uv0.textContent = `UV Index: ${data[0].uv}`;
    dayZeroList.appendChild(avgHumidity0);
    dayZeroList.appendChild(avgTemp0);
    dayZeroList.appendChild(maxTemp0);
    dayZeroList.appendChild(mintemp0);
    dayZeroList.appendChild(avgvis0);
    dayZeroList.appendChild(maxWind0);
    dayZeroList.appendChild(rainChance0);
    dayZeroList.appendChild(precip0);
    dayZeroList.appendChild(snowChance0);
    dayZeroList.appendChild(totalSnow0);
    dayZeroList.appendChild(uv0);
    dayZeroList.appendChild(moonPhase0);
    dayZeroList.appendChild(moonRise0);
    dayZeroList.appendChild(moonSet0);
    dayZeroList.appendChild(sunRise0);
    dayZeroList.appendChild(sunSet0);
    dayZeroDiv.appendChild(dayZeroList);
    forecastDataDiv.appendChild(dayZeroDiv);

    const dayOneDiv = document.createElement('div');
    const dayOneHeader = document.createElement('h4');
    dayOneHeader.textContent = ` Forecast data for tomorrow: ${data[1].date}`;
    dayOneDiv.appendChild(dayOneHeader);
    const dayOneImg = document.createElement('img');
    dayOneImg.src = `http:${data[1].icon}`;
    dayOneDiv.appendChild(dayOneImg);
    const dayOneDesc = document.createElement('p');
    dayOneDesc.textContent = `Forecast: ${data[1].text}`;
    dayOneDiv.appendChild(dayOneDesc);
    const dayOneList = document.createElement('ul');
    const avgHumidity1 = document.createElement('li');
    avgHumidity1.textContent = `Humidity: ${data[1].avghumidity}%`;
    const avgTemp1 = document.createElement('li');
    avgTemp1.textContent = `Average Temp: ${data[1].avgtemp_f}°F`;
    const avgvis1 = document.createElement('li');
    avgvis1.textContent = `Average Visibility: ${data[1].avgvis_miles} miles`;
    const rainChance1 = document.createElement('li');
    rainChance1.textContent = `Chance of Rain: ${data[1].daily_chance_of_rain}%`;
    const snowChance1 = document.createElement('li');
    snowChance1.textContent = `Chance of Snow: ${data[1].daily_chance_of_snow}%`;
    const maxTemp1 = document.createElement('li');
    maxTemp1.textContent = `Max Temp: ${data[1].maxtemp_f}°F`;
    const maxWind1 = document.createElement('li');
    maxWind1.textContent = `Max Wind Speed: ${data[1].maxwind_mph}`;
    const mintemp1 = document.createElement('li');
    mintemp1.textContent = `Min Temp: ${data[1].mintemp_f}°F`;
    const moonPhase1 = document.createElement('li');
    moonPhase1.textContent = `Moon Phase: ${data[1].moon_phase}`;
    const moonRise1 = document.createElement('li');
    moonRise1.textContent = `Moonrise: ${data[1].moonrise}`;
    const moonSet1 = document.createElement('li');
    moonSet1.textContent = `Moonset: ${data[1].moonset}`;
    const sunRise1 = document.createElement('li');
    sunRise1.textContent = `Sunrise: ${data[1].sunrise}`;
    const sunSet1 = document.createElement('li');
    sunSet1.textContent = `Sunset: ${data[1].sunset}`;
    const precip1 = document.createElement('li');
    precip1.textContent = `Total Precipitation: ${data[1].totalprecip_in} inches`;
    const totalSnow1 = document.createElement('li');
    totalSnow1.textContent = `Total Snow: ${data[1].totalsnow_cm} cm`;
    const uv1 = document.createElement('li');
    uv1.textContent = `UV Index: ${data[1].uv}`;
    dayOneList.appendChild(avgHumidity1);
    dayOneList.appendChild(avgTemp1);
    dayOneList.appendChild(maxTemp1);
    dayOneList.appendChild(mintemp1);
    dayOneList.appendChild(avgvis1);
    dayOneList.appendChild(maxWind1);
    dayOneList.appendChild(rainChance1);
    dayOneList.appendChild(precip1);
    dayOneList.appendChild(snowChance1);
    dayOneList.appendChild(totalSnow1);
    dayOneList.appendChild(uv1);
    dayOneList.appendChild(moonPhase1);
    dayOneList.appendChild(moonRise1);
    dayOneList.appendChild(moonSet1);
    dayOneList.appendChild(sunRise1);
    dayOneList.appendChild(sunSet1);
    dayOneDiv.appendChild(dayOneList);
    forecastDataDiv.appendChild(dayOneDiv);

    const dayTwoDiv = document.createElement('div');
    const dayTwoHeader = document.createElement('h4');
    dayTwoHeader.textContent = `Forecast data for: ${data[2].date}`;
    dayTwoDiv.appendChild(dayTwoHeader);
    const dayTwoImg = document.createElement('img');
    dayTwoImg.src = `http:${data[2].icon}`;
    dayTwoDiv.appendChild(dayTwoImg);
    const dayTwoDesc = document.createElement('p');
    dayTwoDesc.textContent = `Forecast: ${data[2].text}`;
    dayTwoDiv.appendChild(dayTwoDesc);
    const dayTwoList = document.createElement('ul');
    const avgHumidity2 = document.createElement('li');
    avgHumidity2.textContent = `Humidity: ${data[2].avghumidity}%`;
    const avgTemp2 = document.createElement('li');
    avgTemp2.textContent = `Average Temp: ${data[2].avgtemp_f}°F`;
    const avgvis2 = document.createElement('li');
    avgvis2.textContent = `Average Visibility: ${data[2].avgvis_miles} miles`;
    const rainChance2 = document.createElement('li');
    rainChance2.textContent = `Chance of Rain: ${data[2].daily_chance_of_rain}%`;
    const snowChance2 = document.createElement('li');
    snowChance2.textContent = `Chance of Snow: ${data[2].daily_chance_of_snow}%`;
    const maxTemp2 = document.createElement('li');
    maxTemp2.textContent = `Max Temp: ${data[2].maxtemp_f}°F`;
    const maxWind2 = document.createElement('li');
    maxWind2.textContent = `Max Wind Speed: ${data[2].maxwind_mph}`;
    const mintemp2 = document.createElement('li');
    mintemp2.textContent = `Min Temp: ${data[2].mintemp_f}°F`;
    const moonPhase2 = document.createElement('li');
    moonPhase2.textContent = `Moon Phase: ${data[2].moon_phase}`;
    const moonRise2 = document.createElement('li');
    moonRise2.textContent = `Moonrise: ${data[2].moonrise}`;
    const moonSet2 = document.createElement('li');
    moonSet2.textContent = `Moonset: ${data[2].moonset}`;
    const sunRise2 = document.createElement('li');
    sunRise2.textContent = `Sunrise: ${data[2].sunrise}`;
    const sunSet2 = document.createElement('li');
    sunSet2.textContent = `Sunset: ${data[2].sunset}`;
    const precip2 = document.createElement('li');
    precip2.textContent = `Total Precipitation: ${data[2].totalprecip_in} inches`;
    const totalSnow2 = document.createElement('li');
    totalSnow2.textContent = `Total Snow: ${data[2].totalsnow_cm} cm`;
    const uv2 = document.createElement('li');
    uv2.textContent = `UV Index: ${data[2].uv}`;
    dayTwoList.appendChild(avgHumidity2);
    dayTwoList.appendChild(avgTemp2);
    dayTwoList.appendChild(maxTemp2);
    dayTwoList.appendChild(mintemp2);
    dayTwoList.appendChild(avgvis2);
    dayTwoList.appendChild(maxWind2);
    dayTwoList.appendChild(rainChance2);
    dayTwoList.appendChild(precip2);
    dayTwoList.appendChild(snowChance2);
    dayTwoList.appendChild(totalSnow2);
    dayTwoList.appendChild(uv2);
    dayTwoList.appendChild(moonPhase2);
    dayTwoList.appendChild(moonRise2);
    dayTwoList.appendChild(moonSet2);
    dayTwoList.appendChild(sunRise2);
    dayTwoList.appendChild(sunSet2);
    dayTwoDiv.appendChild(dayTwoList);
    forecastDataDiv.appendChild(dayTwoDiv);

    contentDiv.appendChild(forecastDataDiv);
  }).catch((error) => {
    emptyContainer();
    console.error(error);
  });
};

const displayForecastDataMetric = () => {
  const contentDiv = document.getElementById('content');
  const forecastDataDiv = document.createElement('div');
  forecastDataDiv.id = 'forecast';
  parseForecastWeatherData().then((data) => {
    console.log(data);
    const dayZeroDiv = document.createElement('div');
    const dayZeroHeader = document.createElement('h4');
    dayZeroHeader.textContent = `Forecast data for today: ${data[0].date}`;
    dayZeroDiv.appendChild(dayZeroHeader);
    const dayZeroImg = document.createElement('img');
    dayZeroImg.src = `http:${data[0].icon}`;
    dayZeroDiv.appendChild(dayZeroImg);
    const dayZeroDesc = document.createElement('p');
    dayZeroDesc.textContent = `Forecast: ${data[0].text}`;
    dayZeroDiv.appendChild(dayZeroDesc);
    const dayZeroList = document.createElement('ul');
    const avgHumidity0 = document.createElement('li');
    avgHumidity0.textContent = `Humidity: ${data[0].avghumidity}%`;
    const avgTemp0 = document.createElement('li');
    avgTemp0.textContent = `Average Temp: ${data[0].avgtemp_c}°C`;
    const avgvis0 = document.createElement('li');
    avgvis0.textContent = `Average Visibility: ${data[0].avgvis_km} KM`;
    const rainChance0 = document.createElement('li');
    rainChance0.textContent = `Chance of Rain: ${data[0].daily_chance_of_rain}%`;
    const snowChance0 = document.createElement('li');
    snowChance0.textContent = `Chance of Snow: ${data[0].daily_chance_of_snow}%`;
    const maxTemp0 = document.createElement('li');
    maxTemp0.textContent = `Max Temp: ${data[0].maxtemp_c}°C`;
    const maxWind0 = document.createElement('li');
    maxWind0.textContent = `Max Wind Speed: ${data[0].maxwind_kph}`;
    const mintemp0 = document.createElement('li');
    mintemp0.textContent = `Min Temp: ${data[0].mintemp_c}°C`;
    const moonPhase0 = document.createElement('li');
    moonPhase0.textContent = `Moon Phase: ${data[0].moon_phase}`;
    const moonRise0 = document.createElement('li');
    moonRise0.textContent = `Moonrise: ${data[0].moonrise}`;
    const moonSet0 = document.createElement('li');
    moonSet0.textContent = `Moonset: ${data[0].moonset}`;
    const sunRise0 = document.createElement('li');
    sunRise0.textContent = `Sunrise: ${data[0].sunrise}`;
    const sunSet0 = document.createElement('li');
    sunSet0.textContent = `Sunset: ${data[0].sunset}`;
    const precip0 = document.createElement('li');
    precip0.textContent = `Total Precipitation: ${data[0].totalprecip_mm} millimeters`;
    const totalSnow0 = document.createElement('li');
    totalSnow0.textContent = `Total Snow: ${data[0].totalsnow_cm} cm`;
    const uv0 = document.createElement('li');
    uv0.textContent = `UV Index: ${data[0].uv}`;
    dayZeroList.appendChild(avgHumidity0);
    dayZeroList.appendChild(avgTemp0);
    dayZeroList.appendChild(maxTemp0);
    dayZeroList.appendChild(mintemp0);
    dayZeroList.appendChild(avgvis0);
    dayZeroList.appendChild(maxWind0);
    dayZeroList.appendChild(rainChance0);
    dayZeroList.appendChild(precip0);
    dayZeroList.appendChild(snowChance0);
    dayZeroList.appendChild(totalSnow0);
    dayZeroList.appendChild(uv0);
    dayZeroList.appendChild(moonPhase0);
    dayZeroList.appendChild(moonRise0);
    dayZeroList.appendChild(moonSet0);
    dayZeroList.appendChild(sunRise0);
    dayZeroList.appendChild(sunSet0);
    dayZeroDiv.appendChild(dayZeroList);
    forecastDataDiv.appendChild(dayZeroDiv);

    const dayOneDiv = document.createElement('div');
    const dayOneHeader = document.createElement('h4');
    dayOneHeader.textContent = ` Forecast data for tomorrow: ${data[1].date}`;
    dayOneDiv.appendChild(dayOneHeader);
    const dayOneImg = document.createElement('img');
    dayOneImg.src = `http:${data[1].icon}`;
    dayOneDiv.appendChild(dayOneImg);
    const dayOneDesc = document.createElement('p');
    dayOneDesc.textContent = `Forecast: ${data[1].text}`;
    dayOneDiv.appendChild(dayOneDesc);
    const dayOneList = document.createElement('ul');
    const avgHumidity1 = document.createElement('li');
    avgHumidity1.textContent = `Humidity: ${data[1].avghumidity}%`;
    const avgTemp1 = document.createElement('li');
    avgTemp1.textContent = `Average Temp: ${data[1].avgtemp_c}°C`;
    const avgvis1 = document.createElement('li');
    avgvis1.textContent = `Average Visibility: ${data[1].avgvis_km} KM`;
    const rainChance1 = document.createElement('li');
    rainChance1.textContent = `Chance of Rain: ${data[1].daily_chance_of_rain}%`;
    const snowChance1 = document.createElement('li');
    snowChance1.textContent = `Chance of Snow: ${data[1].daily_chance_of_snow}%`;
    const maxTemp1 = document.createElement('li');
    maxTemp1.textContent = `Max Temp: ${data[1].maxtemp_c}°C`;
    const maxWind1 = document.createElement('li');
    maxWind1.textContent = `Max Wind Speed: ${data[1].maxwind_kph}`;
    const mintemp1 = document.createElement('li');
    mintemp1.textContent = `Min Temp: ${data[1].mintemp_c}°C`;
    const moonPhase1 = document.createElement('li');
    moonPhase1.textContent = `Moon Phase: ${data[1].moon_phase}`;
    const moonRise1 = document.createElement('li');
    moonRise1.textContent = `Moonrise: ${data[1].moonrise}`;
    const moonSet1 = document.createElement('li');
    moonSet1.textContent = `Moonset: ${data[1].moonset}`;
    const sunRise1 = document.createElement('li');
    sunRise1.textContent = `Sunrise: ${data[1].sunrise}`;
    const sunSet1 = document.createElement('li');
    sunSet1.textContent = `Sunset: ${data[1].sunset}`;
    const precip1 = document.createElement('li');
    precip1.textContent = `Total Precipitation: ${data[1].totalprecip_mm} millimeters`;
    const totalSnow1 = document.createElement('li');
    totalSnow1.textContent = `Total Snow: ${data[1].totalsnow_cm} cm`;
    const uv1 = document.createElement('li');
    uv1.textContent = `UV Index: ${data[1].uv}`;
    dayOneList.appendChild(avgHumidity1);
    dayOneList.appendChild(avgTemp1);
    dayOneList.appendChild(maxTemp1);
    dayOneList.appendChild(mintemp1);
    dayOneList.appendChild(avgvis1);
    dayOneList.appendChild(maxWind1);
    dayOneList.appendChild(rainChance1);
    dayOneList.appendChild(precip1);
    dayOneList.appendChild(snowChance1);
    dayOneList.appendChild(totalSnow1);
    dayOneList.appendChild(uv1);
    dayOneList.appendChild(moonPhase1);
    dayOneList.appendChild(moonRise1);
    dayOneList.appendChild(moonSet1);
    dayOneList.appendChild(sunRise1);
    dayOneList.appendChild(sunSet1);
    dayOneDiv.appendChild(dayOneList);
    forecastDataDiv.appendChild(dayOneDiv);

    const dayTwoDiv = document.createElement('div');
    const dayTwoHeader = document.createElement('h4');
    dayTwoHeader.textContent = `Forecast data for: ${data[2].date}`;
    dayTwoDiv.appendChild(dayTwoHeader);
    const dayTwoImg = document.createElement('img');
    dayTwoImg.src = `http:${data[2].icon}`;
    dayTwoDiv.appendChild(dayTwoImg);
    const dayTwoDesc = document.createElement('p');
    dayTwoDesc.textContent = `Forecast: ${data[2].text}`;
    dayTwoDiv.appendChild(dayTwoDesc);
    const dayTwoList = document.createElement('ul');
    const avgHumidity2 = document.createElement('li');
    avgHumidity2.textContent = `Humidity: ${data[2].avghumidity}%`;
    const avgTemp2 = document.createElement('li');
    avgTemp2.textContent = `Average Temp: ${data[2].avgtemp_c}°C`;
    const avgvis2 = document.createElement('li');
    avgvis2.textContent = `Average Visibility: ${data[2].avgvis_km} KM`;
    const rainChance2 = document.createElement('li');
    rainChance2.textContent = `Chance of Rain: ${data[2].daily_chance_of_rain}%`;
    const snowChance2 = document.createElement('li');
    snowChance2.textContent = `Chance of Snow: ${data[2].daily_chance_of_snow}%`;
    const maxTemp2 = document.createElement('li');
    maxTemp2.textContent = `Max Temp: ${data[2].maxtemp_c}°C`;
    const maxWind2 = document.createElement('li');
    maxWind2.textContent = `Max Wind Speed: ${data[2].maxwind_kph}`;
    const mintemp2 = document.createElement('li');
    mintemp2.textContent = `Min Temp: ${data[2].mintemp_c}°C`;
    const moonPhase2 = document.createElement('li');
    moonPhase2.textContent = `Moon Phase: ${data[2].moon_phase}`;
    const moonRise2 = document.createElement('li');
    moonRise2.textContent = `Moonrise: ${data[2].moonrise}`;
    const moonSet2 = document.createElement('li');
    moonSet2.textContent = `Moonset: ${data[2].moonset}`;
    const sunRise2 = document.createElement('li');
    sunRise2.textContent = `Sunrise: ${data[2].sunrise}`;
    const sunSet2 = document.createElement('li');
    sunSet2.textContent = `Sunset: ${data[2].sunset}`;
    const precip2 = document.createElement('li');
    precip2.textContent = `Total Precipitation: ${data[2].totalprecip_mm} millimeters`;
    const totalSnow2 = document.createElement('li');
    totalSnow2.textContent = `Total Snow: ${data[2].totalsnow_cm} cm`;
    const uv2 = document.createElement('li');
    uv2.textContent = `UV Index: ${data[2].uv}`;
    dayTwoList.appendChild(avgHumidity2);
    dayTwoList.appendChild(avgTemp2);
    dayTwoList.appendChild(maxTemp2);
    dayTwoList.appendChild(mintemp2);
    dayTwoList.appendChild(avgvis2);
    dayTwoList.appendChild(maxWind2);
    dayTwoList.appendChild(rainChance2);
    dayTwoList.appendChild(precip2);
    dayTwoList.appendChild(snowChance2);
    dayTwoList.appendChild(totalSnow2);
    dayTwoList.appendChild(uv2);
    dayTwoList.appendChild(moonPhase2);
    dayTwoList.appendChild(moonRise2);
    dayTwoList.appendChild(moonSet2);
    dayTwoList.appendChild(sunRise2);
    dayTwoList.appendChild(sunSet2);
    dayTwoDiv.appendChild(dayTwoList);
    forecastDataDiv.appendChild(dayTwoDiv);

    contentDiv.appendChild(forecastDataDiv);
  }).catch((error) => {
    emptyContainer();
    console.error(error);
  });
};

const buildWeatherLocationData = () => {
  parseCurrentWeatherData().then((data) => {
    const contentDiv = document.getElementById('content');
    const locationDataDiv = document.createElement('div');
    const locationHeader = document.createElement('h4');
    locationHeader.textContent = `Location Data For: ${data.name}`;
    const locationData = document.createElement('ul');
    const city = document.createElement('li');
    city.textContent = `City: ${data.name}`;
    const region = document.createElement('li');
    region.textContent = `Region: ${data.region}`;
    const country = document.createElement('li');
    country.textContent = `Country: ${data.country}`;
    const lat = document.createElement('li');
    lat.textContent = `Latitude: ${data.lat}°`;
    const lon = document.createElement('li');
    lon.textContent = `Longitude: ${data.lon}°`;
    const tz = document.createElement('li');
    tz.textContent = `Timezone: ${data.tz_id}`;
    const time = document.createElement('li');
    time.textContent = `Local time: ${data.localtime}`;
    locationData.appendChild(city);
    locationData.appendChild(region);
    locationData.appendChild(country);
    locationData.appendChild(lat);
    locationData.appendChild(lon);
    locationData.appendChild(tz);
    locationData.appendChild(time);
    locationDataDiv.appendChild(locationHeader);
    locationDataDiv.appendChild(locationData);
    contentDiv.appendChild(locationDataDiv);
  });
};

export const displayCurrentWeatherDataMetric = () => {
  emptyContainer();
  resetError();
  buildWeatherLocationData();
  parseCurrentWeatherData().then((data) => {
    const contentDiv = document.getElementById('content');
    const weatherDataDiv = document.createElement('div');
    const switchImperial = document.createElement('button');
    switchImperial.id = 'switch';
    switchImperial.textContent = 'Switch To Imperial Data';
    switchImperial.addEventListener('click', displayCurrentWeatherDataImperial);
    weatherDataDiv.appendChild(switchImperial);
    const weatherDataHeader = document.createElement('h4');
    weatherDataHeader.textContent = `Weather data for ${data.name}: `;
    const weatherData = document.createElement('ul');
    const temp = document.createElement('li');
    temp.textContent = `Temp: ${data.temp_c}°C`;
    const timeOfDay = document.createElement('li');
    if (data.is_day === 1) {
      timeOfDay.textContent = 'Daytime';
    } else {
      timeOfDay.textContent = 'Nighttime';
    }
    const desc = document.createElement('li');
    desc.textContent = `Condition: ${data.text}`;
    const icon = document.createElement('img');
    icon.src = `http:${data.icon}`;
    const windSpd = document.createElement('li');
    windSpd.textContent = `Wind Speed: ${data.wind_kph} kph`;
    const windDeg = document.createElement('li');
    windDeg.textContent = `Wind Degree: ${data.wind_degree}`;
    const pressure = document.createElement('li');
    pressure.textContent = `Pressure: ${data.pressure_mb} millibar`;
    const precip = document.createElement('li');
    precip.textContent = `Precipitation: ${data.precip_mm} millimeters`;
    const humidity = document.createElement('li');
    humidity.textContent = `Humidity: ${data.humidity}%`;
    const feelsLike = document.createElement('li');
    feelsLike.textContent = `Feels like: ${data.feelslike_c}°C`;
    const visibility = document.createElement('li');
    visibility.textContent = `Visibility: ${data.vis_km} kilometers`;
    const uv = document.createElement('li');
    uv.textContent = `UV Index: ${data.uv}`;
    const gust = document.createElement('li');
    gust.textContent = `Gust Speed: ${data.gust_kph} kph`;
    weatherData.appendChild(temp);
    weatherData.appendChild(timeOfDay);
    weatherData.appendChild(desc);
    weatherData.appendChild(icon);
    weatherData.appendChild(windSpd);
    weatherData.appendChild(windDeg);
    weatherData.appendChild(pressure);
    weatherData.appendChild(precip);
    weatherData.appendChild(humidity);
    weatherData.appendChild(feelsLike);
    weatherData.appendChild(visibility);
    weatherData.appendChild(uv);
    weatherData.appendChild(gust);
    weatherDataDiv.appendChild(weatherDataHeader);
    weatherDataDiv.appendChild(weatherData);
    contentDiv.appendChild(weatherDataDiv);
  }).catch((error) => {
    emptyContainer();
    console.error(error);
  });
  displayForecastDataMetric();
};

export const displayCurrentWeatherDataImperial = () => {
  emptyContainer();
  resetError();
  buildWeatherLocationData();
  parseCurrentWeatherData().then((data) => {
    const contentDiv = document.getElementById('content');
    const weatherDataDiv = document.createElement('div');
    const switchMetric = document.createElement('button');
    switchMetric.id = 'switch';
    switchMetric.textContent = 'Switch To Metric Data';
    switchMetric.addEventListener('click', displayCurrentWeatherDataMetric);
    weatherDataDiv.appendChild(switchMetric);
    const weatherDataHeader = document.createElement('h4');
    weatherDataHeader.textContent = `Weather data for ${data.name}: `;
    const weatherData = document.createElement('ul');
    const temp = document.createElement('li');
    temp.textContent = `Temp: ${data.temp_f}°F`;
    const timeOfDay = document.createElement('li');
    if (data.is_day === 1) {
      timeOfDay.textContent = 'Daytime';
    } else {
      timeOfDay.textContent = 'Nighttime';
    }
    const desc = document.createElement('li');
    desc.textContent = `Condition: ${data.text}`;
    const icon = document.createElement('img');
    icon.src = `http:${data.icon}`;
    const windSpd = document.createElement('li');
    windSpd.textContent = `Wind Speed: ${data.wind_mph} mph`;
    const windDeg = document.createElement('li');
    windDeg.textContent = `Wind Degree: ${data.wind_degree}`;
    const pressure = document.createElement('li');
    pressure.textContent = `Pressure: ${data.pressure_in} inches`;
    const precip = document.createElement('li');
    precip.textContent = `Precipitation: ${data.precip_in} inches`;
    const humidity = document.createElement('li');
    humidity.textContent = `Humidity: ${data.humidity}%`;
    const feelsLike = document.createElement('li');
    feelsLike.textContent = `Feels like: ${data.feelslike_f}°F`;
    const visibility = document.createElement('li');
    visibility.textContent = `Visibility: ${data.vis_miles} miles`;
    const uv = document.createElement('li');
    uv.textContent = `UV Index: ${data.uv}`;
    const gust = document.createElement('li');
    gust.textContent = `Gust Speed: ${data.gust_mph} mph`;
    weatherData.appendChild(temp);
    weatherData.appendChild(timeOfDay);
    weatherData.appendChild(desc);
    weatherData.appendChild(icon);
    weatherData.appendChild(windSpd);
    weatherData.appendChild(windDeg);
    weatherData.appendChild(pressure);
    weatherData.appendChild(precip);
    weatherData.appendChild(humidity);
    weatherData.appendChild(feelsLike);
    weatherData.appendChild(visibility);
    weatherData.appendChild(uv);
    weatherData.appendChild(gust);
    weatherDataDiv.appendChild(weatherDataHeader);
    weatherDataDiv.appendChild(weatherData);
    contentDiv.appendChild(weatherDataDiv);
    displayForecastDataImperial();
  }).catch((error) => {
    console.error(error);
    emptyContainer();
  });
};